#   NumPy (Numeric Python 或 Numerical Python)
製作者：賴志宏   
建立日期：2017.11.05  
最後修改日期: 2020.11.04

## Numpy

In [ ]:
* NumPy 提供一維、二維、和多維的陣列物件，與相關延伸的物件
* 支援高效率陣列的數學、邏輯、維度操作、排序、選取元素，和基本線性岱術語統計等多種數學函式的函式庫

NumPy 的核心是ndarray，他是相同資料型態元素所組成的陣列，與Python的清單List之差異為： 
* 資料結構和C語言一樣，為元素數目固定，且所屬的元素都是同一種資料型別 (python的list允許不同的資料型別，且元素數目可以變動)  
* NumPy陣列是固定尺寸，若是更改物件尺寸就是重新建立全新的陣列，Python的List是容器，不用指定尺寸


In [ ]:
為什麼使用NumPy& Pandas:
.支援多維陣列與矩陣運算，針對陣列提供大量的數學函式，方便處理數學問題，例如傅立葉轉換、線性代數、多項式等
.運算速度快:numpy和pandas 都是採用C 語言編寫, pandas 又是基於numpy, 是numpy的升級版，且採用的是矩陣運算，會比python 自帶的字典或者列表快好多
.消耗資源少

In [ ]:
### 顯示函式的說明文件

* numpy.函式名稱?
* numpy.sin?

In [10]:
import numpy as np
np.sin?
print(1)

1


### official website:
http://www.numpy.org/
    

In [4]:
# show numpy version
import numpy
numpy.__version__

'1.13.3'

In [1]:
# 使用 import .. as ..
import numpy as np
arr1 = np.array([10, 15, 20])
print(arr1)
print(type(arr1))

[10 15 20]
<class 'numpy.ndarray'>


### Basic properties:

* NumPy套件所提供的陣列型別稱為 ndarray (n-dimension array)  
* ndarray型別的重要屬性：   
 * ndarray.ndim:陣列的維度  
 * ndarray.shape:陣列的形狀(用tuple表示)，每個整數表示各維度的元素個數  
 * ndarray.size:元素的個數  
 * ndarray.dtype:元素的資料型別，包含python內建的int, bool, str等，註：type()是看整個物件的資料型別  
     也可以是NumPy套件提供的numpy.int32, numpy.int16, numpy.float64等  
 * ndarray.itemsize:陣列元素的位元組數  

In [4]:
import numpy as np 
array = np.array([[1,2,3],[4,5,6]])  
print(array, '\n')
print('維度:',array.ndim) 
print('行列:',array.shape) # 列與行數
print('行列:',array.shape[0]) # 列數 (row number)
print('行列:',array.shape[1]) # 行數 (column number)
print('元素的個數:',array.size) 
print('array[0]元素的個數:',array[0].size) 
print('元素的資料型別:',array.dtype) # 看每個元素的資料型態
print('元素的位元組數:',array.itemsize) 
print(type(array))   # 看整個資料的資料型態

[[1 2 3]
 [4 5 6]] 

維度: 2
行列: (2, 3)
行列: 2
行列: 3
元素的個數: 6
array[0]元素的個數: 3
元素的資料型別: int32
元素的位元組數: 4
<class 'numpy.ndarray'>


### 建立一維陣列的方式:
1. 使用array()將其它格式的資料轉為陣列：
 * a = np.array([1, 3, 5, 7, 9])  # 將串列list轉為numpy陣列，每個元素為整數  
 * b = np.array((1, 3, 5, 7, 9))  # 將元組tuple轉為numpy陣列，每個元素為整數  
 * c = np.array({1, 3, 5, 7, 9})  # 將集合set轉為numpy陣列，每個元素為物件  
 --> 所以：一般是使用清單或元組來建立Numpy的一維陣列
2. 使用arange():(註：Python的range只能用在整數，np.arange可以是浮點數）
    arange(起始值, 終止值, 間隔值, dtype=資料型態)
    其中的參數可以省略，和python的range()使用方法類似   # 不會包含終止值
3. 使用linspace()建立平均分布的數值  # linear space
   linspace(起始值, 終止值, 元素個數, dtype=資料型態)  #會包含終止值
4. 使用其他函式，例如zeros(), ones(), random.random(), np.random.randint()

In [9]:
import numpy as np 
a = np.array([1, 3, 5, 7, 9])
b = np.array((1, 3, 5, 7, 9))
c = np.array({1, 3, 5, 7, 9})
print(a, b, c, end = '\t')
print()
print(a.dtype, b.dtype, c.dtype)   # 看每個元素的資料型態
print()
print(type(a), type(b), type(c))   # 看整個資料的資料型態

a[3] = 100
b[3] = 100
#c[3] = 100  # 會出錯
print(a, b, c, end = '\t')


[1 3 5 7 9] [1 3 5 7 9] {1, 3, 5, 7, 9}	
int32 int32 object

<class 'numpy.ndarray'> <class 'numpy.ndarray'> <class 'numpy.ndarray'>
[  1   3   5 100   9] [  1   3   5 100   9] {1, 3, 5, 7, 9}	

In [11]:
import numpy as np 
arr1 = np.array([5,2,8,4,5,6]) 
arr2 = np.array([5,2,8,4,5,6], dtype = float)
print(arr1, arr2, sep = '\n')
print(arr1.dtype, arr2.dtype)

[5 2 8 4 5 6]
[ 5.  2.  8.  4.  5.  6.]
int32 float64


In [10]:
# 使用arange():
#     arange(起始值, 終止值, 間隔值, dtype=資料型態)
#     其中的參數可以省略，和python的range()使用方法類似   # 不會包含終止值
import numpy as np 
arr1 = np.arange(5)  # 不含5
arr2 = np.arange(3, 10)
arr3 = np.arange(3, 10, 0.5)
arr4 = np.arange(3, 10, 0.8, dtype = float)
print(arr1, arr2, arr3, arr4, sep = '\n')

[0 1 2 3 4]
[3 4 5 6 7 8 9]
[ 3.   3.5  4.   4.5  5.   5.5  6.   6.5  7.   7.5  8.   8.5  9.   9.5]
[ 3.   3.8  4.6  5.4  6.2  7.   7.8  8.6  9.4]


In [3]:
import numpy as np 
arr1 = np.linspace(0, 10, 20)  # 包含 10，注意最後一個引數是指共有20個，也就是分為19個間隔，若是要每個間隔0.5，要使用21
print(arr1)

[  0.           0.52631579   1.05263158   1.57894737   2.10526316
   2.63157895   3.15789474   3.68421053   4.21052632   4.73684211
   5.26315789   5.78947368   6.31578947   6.84210526   7.36842105
   7.89473684   8.42105263   8.94736842   9.47368421  10.        ]


In [23]:
# arange()、zeros()、ones()和full()函數外，還提供更多函數來建立各種預設內容的陣列
import numpy as np
a=np.array([3,6,9,12,15,18])
b=np.arange(6) # 0 .. 6 但不含6
c = np.zeros(6) # 數據全為0，6個
d = np.ones(6, dtype = np.int) # 數據為1，6個，整數
e = np.random.random(6) # 6個亂數 0 .. <1
f = np.random.randint(1, 100, 10) # 10個1至100(不含)的整數，若使用random.randint()會產生包含100（終止值）的亂數，

print(a,b,c,d,e,f, sep="\n")


[ 3  6  9 12 15 18]
[0 1 2 3 4 5]
[ 0.  0.  0.  0.  0.  0.]
[1 1 1 1 1 1]
[ 0.11784684  0.93903155  0.23420872  0.19633984  0.40961686  0.05795418]
[90 62  4 60 31 99 96 25 55 90]


In [7]:
# NumPy的zeros_like()和ones_like()函數可以依據參數的範本陣列形狀，產生相同尺寸元素值都是0或1的陣列，

import numpy as np

a = np.array([[1,2,3],[4,5,6]])
b = np.zeros_like(a)
print(a)
print()
print(b)

print()
c = np.ones_like(a)  
print(c)

print()
d = np.eye(3)  # 對角線都是1
print(d)

print()
e = np.eye(3, k=1)  # 從索引的1開始，對角線都是1，也就是從[0,1]的位置的斜對角開始為1
print(e)

print()
f = np.random.rand(3)
print(f)
print()
g = np.random.rand(3,3)
print(g)  

[[1 2 3]
 [4 5 6]]

[[0 0 0]
 [0 0 0]]

[[1 1 1]
 [1 1 1]]

[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]

[[ 0.  1.  0.]
 [ 0.  0.  1.]
 [ 0.  0.  0.]]

[ 0.59196246  0.16613742  0.04796665]

[[ 0.64410487  0.65770345  0.00733402]
 [ 0.47207714  0.6365783   0.56624903]
 [ 0.31277487  0.02469161  0.34307369]]


In [3]:
# 用某一數字填滿整個陣列

import numpy as np

a = np.full(2, 6)  #有兩個元素，每個都是6
print(a)

print()
b = np.full((3,3), 5)
print(b)

[6 6]

[[5 5 5]
 [5 5 5]
 [5 5 5]]


In [1]:
import numpy as np

f = np.random.randint(1, 100, 10) # 10個1至100(不含)的整數，np.random.randint()不包含終止值100
print(f)

import random
for i in range(100):
    print(random.randint(1, 3), end = " ")  # random.randint()會包含終止值3

[46 68 74 98 76 28 25 38 22 24]
1 2 1 1 1 1 2 2 2 1 3 1 2 2 2 3 3 1 1 3 3 2 2 2 1 1 1 2 3 1 2 3 1 3 2 3 2 2 1 3 1 1 1 1 3 3 1 1 1 3 2 1 3 2 2 3 1 3 3 1 2 1 1 2 3 2 1 1 3 1 3 3 3 1 3 1 3 3 1 3 2 2 1 2 2 2 1 3 1 1 3 1 1 2 1 2 3 2 2 2 

### 多維陣列的建立:
1. 使用numpy.array
   a=np.array([[3,6,9],[12,15,18]])   
2. 先使用上述方法建立一維陣列，再使用reshape()函式轉換成多維陣列:
    

In [32]:
a = np.array([[3,6,9],[12,15,18]])
b = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9]).reshape(3,3)
c = np.random.randint(1, 100, 12).reshape(4,3) # 12個1至100(不含)的整數
d = a.reshape(3, 2)
e = np.arange(1, 16).reshape(3, 5)
print(a,b,c,d,e, sep="\n\n")

[[ 3  6  9]
 [12 15 18]]

[[1 2 3]
 [4 5 6]
 [7 8 9]]

[[51 78  7]
 [70 96 99]
 [34 92 87]
 [25 60 58]]

[[ 3  6]
 [ 9 12]
 [15 18]]

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]


In [2]:
import numpy as np
a=np.array([[3,6,9],[12,15,18]])
b=np.arange(6).reshape(2,3) 
c = np.zeros((2,3)) # 數據全為0，不能用c = np.zeros(2,3)
d = np.ones((2,3), dtype = np.int) # 數據為1，6個
e = np.random.random((2,3)) #亂數，6個
print(a,b,c,d,e, sep="\n")


[[ 3  6  9]
 [12 15 18]]
[[0 1 2]
 [3 4 5]]
[[ 0.  0.  0.]
 [ 0.  0.  0.]]
[[1 1 1]
 [1 1 1]]
[[ 0.09531017  0.96015661  0.50065818]
 [ 0.35205021  0.56587427  0.01304847]]


## 走訪陣列

In [5]:
import numpy as np

a = np.array([1, 2, 3, 4, 5])
for ele in a:
    print(ele)

1
2
3
4
5


In [6]:
import numpy as np

a = np.array([[1, 2], [3, 4], [5, 6]])
for ele in a:
    print(ele)

for ele in a:
    for item in ele:
        print(str(item), end="  ")

[1 2]
[3 4]
[5 6]
1  2  3  4  5  6  

## 取出子陣列

In [4]:
import numpy as np

a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
print("a=" + str(a))    # str(a) 內容為'[1 2 3 4 5 6 7 8 9]'

b = a[1:3]     # 索引 1,2
print("a[1:3]=" + str(b))
b = a[:4]      # 索引 0,1,2,3
print("a[:4]=" + str(b))
b = a[3:]      # 索引 3,4,5,6,7,8
print("a[3:]=" + str(b))
b = a[2:9:3]   # 索引 2,5,8
print("a[2:9:3]=" + str(b))
b = a[::2]     # 索引 0,2,4,6,8
print("a[::2]=" + str(b))
b = a[::-1]    # 索引 8,7,6,5,4,3,2,1,0
print("a[::-1]=" + str(b))
b = a[2:-2]    # 索引 8,7,6,5,4,3,2,1,0
print("a[2:-2]=" + str(b))

a=[1 2 3 4 5 6 7 8 9]
a[1:3]=[2 3]
a[:4]=[1 2 3 4]
a[3:]=[4 5 6 7 8 9]
a[2:9:3]=[3 6 9]
a[::2]=[1 3 5 7 9]
a[::-1]=[9 8 7 6 5 4 3 2 1]
a[2:-2]=[3 4 5 6 7]


In [6]:
# 給一個索引清單，取出選擇元素來建立新陣列

import numpy as np

a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
print("a=" + str(a))

print(a[0], a[2], a[-1])  # 索引 0,2,最後1個 
b = a[[1, 3, 5, 7]]       # 索引 1,3,5,7
print("a[[1,3,5,7]]=" + str(b))
b = a[range(6)]           # 索引 0,1,2,3,4,5
print("a[range(6)]=" + str(b))
a[[2, 6]] = 10            # 同時更改多個索引值
print("a[[2,6]]=10->" + str(a))

a=[1 2 3 4 5 6 7 8 9]
1 3 9
a[[1,3,5,7]]=[2 4 6 8]
a[range(6)]=[1 2 3 4 5 6]
a[[2,6]]=10->[ 1  2 10  4  5  6 10  8  9]


In [9]:
# 使用布林陣列，這是相同大小的布林值陣列，如果元素值是True，表示選擇對應的元素；反之False，就不選擇

import numpy as np

a = np.array([14,8,10,11,6,3,18,13,12,9])
print("a=" + str(a))
mask = (a % 3 == 0)        # 建立布林值陣列
print("mask=" + str(mask))
b = a[mask]                # 使用布林值陣列取出值
print("a[mask]=" + str(b))
a[a % 3 == 0] = -1         # 同時更改多個True索引
print("a[a%3==0]=-1->" + str(a))

a=[14  8 10 11  6  3 18 13 12  9]
mask=[False False False False  True  True  True False  True  True]
a[mask]=[ 6  3 18 12  9]
a[a%3==0]=-1->[14  8 10 11 -1 -1 -1 13 -1 -1]


In [12]:
# 使用複雜索引取出元素 

import numpy as np

a = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
print("a=")
print(a)

print()
b = a[[0,1,2],[0,1,0]]   # 索引 [0,0][1,1][2,0]
print("a[[0,1,2],[0,1,0]]=")
print(b)

print()
b = np.array([a[0,0],a[1,1],a[2,0]])  # 索引 [0,0][1,1][2,0]
print("np.array([a[0,0],a[1,1],a[2,0]])=")
print(b)

print()
idx = np.array([0, 2, 0, 1])
print("idx=" + str(idx))
b = a[np.arange(4), idx]     # 索引 [0,0][1,2][2,0][3,1]
print("a[np.arange(4),idx]=")
print(b)

print()
a[np.arange(4), idx] += 10
print("a[np.arange(4), idx] += 10->")
print(a)

a=
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]

a[[0,1,2],[0,1,0]]=
[1 5 7]

np.array([a[0,0],a[1,1],a[2,0]])
[1 5 7]

idx=[0 2 0 1]
a[np.arange(4),idx]=
[ 1  6  7 11]

a[np.arange(4), idx] += 10->
[[11  2  3]
 [ 4  5 16]
 [17  8  9]
 [10 21 12]]


In [17]:
# 使用整數值索引

import numpy as np

a = np.array([[1,2],[3,4],[5,6]])
print("a=")
print(a)

print()
mask = (a > 2)
print("mask=")
print(mask)

b = a[mask]           # 使用布林值陣列取出值
print()
print("a[mask]=" + str(b))

a[a > 2] = -1         # 同時更改多個True索引
print()
print("a[a>2]=-1->")
print(a)

a=
[[1 2]
 [3 4]
 [5 6]]

mask=
[[False False]
 [ True  True]
 [ True  True]]

a[mask]=[3 4 5 6]

a[a>2]=-1->
[[ 1  2]
 [-1 -1]
 [-1 -1]]


## 改變陣列的形狀
1. 廣播:讓不同形狀的陣列執行數學運算
當一個小陣列和一個大陣列時，如果沒有廣播機制，我們需要自行先複製小陣列元素，
將它擴充成與大陣列相同的形狀後，才能執行2個陣列的數學運算，
NumPy廣播機制會自動幫我們擴充小陣列來執行運算

2. 重新設定維度: reshape()

3. 陣列平坦化: ravel()

4. 轉置: .T (或 .transpose())

4. 增加維度: newaxis 

In [17]:
# 廣播
import numpy as np

a = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
print("a=")
print(a)
print("a 形狀: " + str(a.shape))

b = np.array([1,0,1])
print()
print("b=" + str(b))
print("b 形狀: " + str(b.shape))

print()
c = a + b
print('a+b:', c, sep ='\n')

a=
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
a 形狀: (4, 3)

b=[1 0 1]
b 形狀: (3,)

a+b:
[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


In [18]:
# 陣列平坦化:將二維陣列平坦化成一維陣列, python提供兩種格式
# ravel 英文意思為解開線團

import numpy as np

a = np.array([[1,2,3],[4,5,6]])
print("a=")
print(a)

b = a.ravel()
print("a.ravel()=" + str(b))
b = np.ravel(a)
print("np.ravel(a)=" + str(b))

a=
[[1 2 3]
 [4 5 6]]
a.ravel()=[1 2 3 4 5 6]
np.ravel(a)=[1 2 3 4 5 6]
[[1 2 3]
 [4 5 6]]


In [19]:
# .T

import numpy as np

a = np.array([1,2,3,4,5,6])
print("a=" + str(a))

b = np.reshape(a,(3,2))
print("b=np.reshape(a,(3,2))->")
print(b)

print()
c = b.T
print("c=b.T->")
print(c)

print()
d = b.transpose()
print("d=b.transpose()->")
print(d)

print()
e = np.transpose(b)
print("e=np.transpose(b)->")
print(e)

a=[1 2 3 4 5 6]
b=np.reshape(a,(3,2))->
[[1 2]
 [3 4]
 [5 6]]

c=b.T->
[[1 3 5]
 [2 4 6]]

d=b.transpose()->
[[1 3 5]
 [2 4 6]]

e=np.transpose(b)->
[[1 3 5]
 [2 4 6]]


In [22]:
# newaxis 增加維度

import numpy as np

a = np.array([1,2,3])
print("a=" + str(a))

print()
b = a[:, np.newaxis]
print("b=a[:,np.newaxis]->")
print(b)
print('shape:', b.shape)

print()
c = a[np.newaxis, :]
print("c=a[np.newaxis,:]->")
print(c)
print('shape:', c.shape)

a=[1 2 3]

b=a[:,np.newaxis]->
[[1]
 [2]
 [3]]
shape: (3, 1)

c=a[np.newaxis,:]->
[[1 2 3]]
shape: (1, 3)


In [23]:
# 陣列形狀與內容操作 –陣列複製、填滿值和連接陣列

import numpy as np

a = np.array([1,2,3])
print("a=" + str(a))

b = a.copy()   # 不使用 b = a，a和b會指向同一個位址，修改內容時，兩者的內容都會一起改變
print("b=a.copy()->" + str(b))
b.fill(4)
print("b.fill(4)=" + str(b))
c = np.concatenate((a,b))
print("c=np.concatenate((a,b))->" + str(c)) # 


a=[1 2 3]
b=a.copy()->[1 2 3]
b.fill(4)=[4 4 4]
c=np.concatenate((a,b))->[1 2 3 4 4 4]


In [24]:
a = np.array([1,2,3])
b = a    # 用這種方式設定，a和b會指向同一個位址，修改內容時，兩者的內容都會一起改變，所以若是一般的複製，會使用 b = a.copy()
b[0] = 5
print(a)

[5 2 3]


In [23]:
# 使用np.concatenate()函數連接多個二維陣列時，
# 我們可以指定參數axis軸的連接方向，參數值0是直向，可以連接在二維陣列的下方；值1是橫向，預設為0

import numpy as np

a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]])

c = np.concatenate((a,b))
print("c=np.concatenate((a,b))->")
print(c)
c = np.concatenate((a,b), axis=0)
print("c=np.concatenate((a,b), axis=0)->")
print(c)
c = np.concatenate((a,b), axis=1)
print("c=np.concatenate((a,b), axis=1)->")
print(c)

c=np.concatenate((a,b))->
[[1 2]
 [3 4]
 [5 6]
 [7 8]]
c=np.concatenate((a,b), axis=0)->
[[1 2]
 [3 4]
 [5 6]
 [7 8]]
c=np.concatenate((a,b), axis=1)->
[[1 2 5 6]
 [3 4 7 8]]


## 陣列的運算

### universal function (簡稱 ufunc) universal函式

* 意義：NUmpy提供對陣列中全部元素進行運算，並有回傳功能的函式
* 例如：np.sum(), np.square(), np.sin()...

* 註：使用以下方法，在type中可以看到是否屬於ufunc
    * numpy.函式名稱?


In [11]:
import numpy as np

np.sin?

In [3]:
# 陣列與常數的運算

import numpy as np
a=np.array([[3,6,9],[12,15,18]])
b = a +3
print(b)

[[ 6  9 12]
 [15 18 21]]


In [42]:
#兩個陣列的加減乘除法 (*非矩陣乘法*)
import numpy as np
a=np.array([[2,4,6],[8,10,12]])
b=np.arange(1,7).reshape((2,3)) 
print("a:\n", a)
print("\nb:\n", b)
print("\na+b:\n", a+b)
print("\na-b:\n", a-b)
print("\na*b:\n", a*b)
print("\na/b:\n", a/b)

a:
 [[ 2  4  6]
 [ 8 10 12]]

b:
 [[1 2 3]
 [4 5 6]]

a+b:
 [[ 3  6  9]
 [12 15 18]]

a-b:
 [[1 2 3]
 [4 5 6]]

a*b:
 [[ 2  8 18]
 [32 50 72]]

a/b:
 [[ 2.  2.  2.]
 [ 2.  2.  2.]]


In [47]:
import numpy as np
a=np.array([[2,4,6],[8,10,12]])
a = a ** 2  # 平方
print(a)

print()
print(a>10)

[[  4  16  36]
 [ 64 100 144]]

[[False  True  True]
 [ True  True  True]]


In [43]:
# 矩陣乘法 numpy.dot()
import numpy as np
a=np.array([[2,4,6],[8,10,12]])
b=np.arange(6).reshape((2,3)) 
print(a)
print(b.T) # transpose
print(np.dot(a,b.T))

[[ 2  4  6]
 [ 8 10 12]]
[[0 3]
 [1 4]
 [2 5]]
[[ 16  52]
 [ 34 124]]


In [3]:
# 我們可以指定參數axis軸的連接方向，參數值0是直向，可以連接在二維陣列的下方；值1是橫向
import numpy as np
a=np.array([[3,6,9],[12,15,18]])

print(a)
print()
print("sum(a):", np.sum(a))
print("sum(a, axis=1):",np.sum(a, axis=1))

print("sum(a, axis=0):",np.sum(a, axis=0))

print(a.sum(axis = 1))

[[ 3  6  9]
 [12 15 18]]

sum(a): 63
sum(a, axis=1): [18 45]
sum(a, axis=0): [15 21 27]
[18 45]


In [ ]:
concatenate() 可以合併兩個陣列或加入元素

In [51]:
import numpy as np
a = np.array([2,4,6,8,10,12])
b = np.arange(10)
c = np.concatenate((a,b))
d = np.concatenate((a,[10,20]))
print(a,b,c,d, sep="\n\n")

[ 2  4  6  8 10 12]

[0 1 2 3 4 5 6 7 8 9]

[ 2  4  6  8 10 12  0  1  2  3  4  5  6  7  8  9]

[ 2  4  6  8 10 12 10 20]


In [30]:
# Numpy array 合併

import numpy as np
A = np.array([1,1,1])
B = np.array([2,2,2])

print(np.vstack((A,B))) #vertical

print(np.hstack((A,B))) #horizontal, 和np.concatenate((A, B), axis=0)一樣

c = np.concatenate((A, B), axis=0)
print(c)

[[1 1 1]
 [2 2 2]]
[1 1 1 2 2 2]
[1 1 1 2 2 2]


## numpy的亂數

* 格式為： numpy.random.亂數的方法

* seed(int) : 指定亂數函數的種子數，這是整數值，同一個種子數會產生相同的亂數序列
 * seed(5)
* random() : 產生0.0~1.0之間的亂數，如 0.7298076072029743
 * random(5):產生0.0~1.0之間的亂數5個，形成5個元素的串列，如[ 0.58607119  0.37147243  0.05337405  0.49300567  0.10304672]
 * random((3,4)))：產生二維陣列的亂數

* randint(min,max,size) : 產生min~max之間的整數亂數，不含max，如果有第3個參數可以產生此形式的陣列
 * randint(5, 10)：產生5~10之間的整數亂數，不含10
 * randint(5, 10, 6)：產生產生5到10(不含)的整數6個的陣列　[8 7 6 8 6 6]
 * randint(1, 101, (3,4))：產生5到10(不含)的整數3*4個的二維陣列
<pre>
[[ 52  61 100  23]
 [ 18  76   5  85]
 [ 99  96  93  57]] </pre>
 
* rand()： 可以產生亂數值或是多維的陣列
 * rand()：產生0至1之間的小數亂數，例如　0.9760298522559884
 * rand(5)： 5個亂數值的串列，例如：[ 0.64355233  0.06190279  0.0139926   0.49136906  0.18873564]
 * rand(3,2,4)：三維的亂數
<pre>
[[[ 0.03954012  0.44242043  0.14827974  0.56508804]
  [ 0.81026024  0.35193408  0.67416147  0.3857823 ]]

 [[ 0.75199775  0.68688449  0.11550551  0.74191692]
  [ 0.59480112  0.6741724   0.83223916  0.07394322]]

 [[ 0.56966074  0.50914309  0.80103979  0.99366129]
  [ 0.57323325  0.15629903  0.39392062  0.98063935]]] </pre>

* np.random.randn(): 類似rand()，可以產生標準常態分佈的樣本資料
* np.random.normal(loc=xx, scale=xx, size=xx)：功能如同.randn()，但是可以產生各種常態分布的資料，且可以產生亂數的陣列 (loc 為平均數，預設為0，scale為標準差，預設為1，xx表示自由輸入的數字）
 * np.random.normal(10,3,5)  # 產生5個平均數為 10，標準差為 3 的常態分布的亂數
 * np.random.normal(10,3,(2,4)) # 產生二維陣列平均數為 10，標準差為 3 的常態分布的亂數 （共有2*4個）
 
* np.random.choice()
    * 参数意思分别 是从a 中以概率P，随机选择3个, p没有指定的时候相当于是一致的分布，replace = True 表示放回再抽
    * a = list(range(1, 7))
    * print(a)
    * a1 = np.random.choice(a, size=3, replace=False, p=None)
* np.random.shuffle(串列) 
    * 將串列打亂

原文網址：https://kknews.cc/zh-tw/other/29er599.html


In [68]:
# random.randint() 與 numpy.random.randint()之差異
import numpy as np
import random

throws1 = np.random.randint(0, 2)  # exclude 2
throws2 = random.randint(0,2)  # include 2

throws3 = np.random.randint(low=0, high=2, size=10) # 100 random numbers
throws4 = np.random.randint(0, 2, 10)  # 10 random numbers, no argument names
throws5 = np.random.randint(0, 2, (3,4))
print("throws1:", throws1)
print("throws2:", throws2)
print("throws3:", throws3)
print("throws4:", throws4)
print("throws5:", throws5)

throws1: 1
throws2: 0
throws3: [1 1 0 0 1 1 1 0 0 1]
throws4: [1 0 1 0 0 1 0 1 0 1]
throws5: [[0 1 1 0]
 [0 0 1 0]
 [0 0 0 0]]


In [48]:
import numpy as np
print(np.random.rand())
print()

print(np.random.rand(5)) # 5個亂數值的串列
print()

print(np.random.rand(3,2,4))  # 三維的亂數

0.44521689656716035

[ 0.64355233  0.06190279  0.0139926   0.49136906  0.18873564]
[[[ 0.03954012  0.44242043  0.14827974  0.56508804]
  [ 0.81026024  0.35193408  0.67416147  0.3857823 ]]

 [[ 0.75199775  0.68688449  0.11550551  0.74191692]
  [ 0.59480112  0.6741724   0.83223916  0.07394322]]

 [[ 0.56966074  0.50914309  0.80103979  0.99366129]
  [ 0.57323325  0.15629903  0.39392062  0.98063935]]]


In [38]:
import numpy as np
a = np.random.random()
b = np.random.random(5)
print(a, b, c, sep = '\n\n')

0.7298076072029743

[ 0.58607119  0.37147243  0.05337405  0.49300567  0.10304672]


In [73]:
import numpy as np

np.random.seed(293423)

v1 = np.random.random()
v2 = np.random.random()
print(v1, v2)
v3 = np.random.randint(5, 10)  #產生5到10(不含)的整數
v4 = np.random.randint(1, 101)
print(v3, v4)

print()
v5 = np.random.randint(5, 10, 6) # 產生5到10(不含)的整數6個的陣列
v6 = np.random.randint(1, 101, (3,4))#  產生5到10(不含)的整數3*4個的二維陣列
print(v5)
print()
print(v6)
?v6

0.3367724725390667 0.5269343749958971
6 46

[8 7 6 8 6 6]

[[ 52  61 100  23]
 [ 18  76   5  85]
 [ 99  96  93  57]]


In [52]:
import numpy as np
print(np.random.rand())
print()

print(np.random.randn(5)) # 產生標準常態分佈的樣本資料的5個亂數值的串列
print()

print(np.random.randn(3,2,4))  # 三維的亂數

0.6339479026692069

[-0.93049591  1.04473594  1.64123031  2.23609392  1.30637821]

[[[-0.3213905   0.78786166  0.54664495 -0.55368813]
  [ 0.60357311 -1.66238595 -1.9677313  -0.83790247]]

 [[ 0.90846026 -0.84352299  0.51472288 -0.18172246]
  [ 0.49251474 -0.45826979  1.71923274 -0.58883365]]

 [[-0.43799015  0.27047407  0.44568088 -0.78659052]
  [ 0.14839301  0.89480487 -0.5505088  -0.25509628]]]


In [51]:
import numpy as np

a = np.random.rand(5)
print("np.random.rand(5)=")
print(a)

print()
b = np.random.rand(3, 2)  
print("np.random.rand(3,2)=")
print(b)

print()
c = np.random.randint(5, 10, size=5)
print("np.random.randint(5,10,size=5)")  # size =  可以省略
print(c)

print()
d = np.random.randint(5, 10, size=(2,3))
print("np.random.randint(5,10,size=(2,3))")  # size =  可以省略，如下面的敘述
print(d)

print()
d = np.random.randint(5, 10, (2,3))
print("np.random.randint(5,10,size=(2,3))") 
print(d)

np.random.rand(5)=
[ 0.8068195   0.12312116  0.41897774  0.83926102  0.08700079]

np.random.rand(3,2)=
[[ 0.58711123  0.32912915]
 [ 0.58584619  0.41105227]
 [ 0.47067953  0.58013819]]

np.random.randint(5,10,size=5)
[5 5 5 8 7]

np.random.randint(5,10,size=(2,3))
[[8 7 9]
 [5 7 7]]

np.random.randint(5,10,size=(2,3))
[[7 9 5]
 [9 8 8]]


In [26]:
# 三角函式

import numpy as np

a = np.array([30,45,60]) 

print(np.sin(a*np.pi/180)) 
print(np.cos(a*np.pi/180)) 
print(np.tan(a*np.pi/180)) 

[ 0.5         0.70710678  0.8660254 ]
[ 0.8660254   0.70710678  0.5       ]
[ 0.57735027  1.          1.73205081]


In [59]:
#  around()函數是四捨五入函數，第2個參數指定四捨五入是哪一個十進位值的位數，預設值是0（沒有小數），1是小數點下一位；-1是10進位
# floor() 和　ceil()只有一個引數

import numpy as np

a = np.array([1.0,5.55, 123, 0.567, 25.532]) 
print("a=" + str(a))

print(np.around(a))
print(np.around(a, 1))
print(np.around(a, -1))

a = np.array([-1.7, 1.5, -0.2, 0.6, 10]) 
print("a=" + str(a))

b = np.floor(a)

print("floor()=" + str(b))
b = np.ceil(a)
print("ceil()=" + str(b))

a=[   1.       5.55   123.       0.567   25.532]
[   1.    6.  123.    1.   26.]
[   1.     5.6  123.     0.6   25.5]
[   0.   10.  120.    0.   30.]
a=[ -1.7   1.5  -0.2   0.6  10. ]
floor()=[ -2.   1.  -1.   0.  10.]
ceil()=[ -1.   2.  -0.   1.  10.]


## NumPy的通用函式

### NumPy針對陣列提供許多通用函式，例如：
* add(x1, x2) 
* subtract(x1, x2) 
* multiply(x1, x2) 
* divide(x1, x2) 
* mod(x1, x2) 
* power(x1, x2)
* isfinite(x) 
* isinf(x) 
* isnan(x) 
* sign(x)
* negative(x) 
* absolute(x) 
* sum(x) 
* max(x) 
* min(x) 

* rint(x) 
* floor(x) 
* ceil(x) 
* sqrt(x) 
* square(x) 
* exp(x) 
* exp2(x) 
* log(x) 
* log2(x) 
* log10(x) 
* cos(x)、sin(x)、tan(x)、acos(x)、asin(x)、atan(x) 等三角函式
* mean(x) 
    * 含遺漏值的平均數：np.mean(dataframe物件或欄位)
    * 不含遺漏值的平均數： np.nanmean(dataframe物件或欄位)
* median(x)  中位數
    * 含遺漏值的中數：np.median(dataframe物件或欄位)
    * 不含遺漏值的中數： np.nanmedian(dataframe物件或欄位)
* std(x)
    * 分為母數推估和樣本的標準差兩種，參見統計課程中的講義


## 檔案儲存與載入

In [ ]:
# 將陣列儲存成檔案


In [24]:
# 使用二進位檔寫入， 使用save

import numpy as np

a = np.arange(10)
outputfile = "Example.npy"
with open(outputfile, 'wb') as fp:
    np.save(fp, a)

In [60]:
#  設定分隔字元，delimiter=','
# savetxt 儲存成 CSV格式
import numpy as np

a = np.array([[1,2,3],[4,5,6]])
outputfile = "Example.out"
np.savetxt(outputfile, a, delimiter=',')

In [ ]:
# Example.out
1.000000000000000000e+00,2.000000000000000000e+00,3.000000000000000000e+00
4.000000000000000000e+00,5.000000000000000000e+00,6.000000000000000000e+00

In [63]:
#  設定分隔字元，delimiter=','
# savetxt 儲存成 CSV格式
import numpy as np

a = np.array([[1,2,3],[4,5,6]], dtype = int)
outputfile = "Example.out"
np.savetxt(outputfile, a, delimiter=',')
print(a)

[[1 2 3]
 [4 5 6]]


In [ ]:
# Example.out
1.000000000000000000e+00,2.000000000000000000e+00,3.000000000000000000e+00
4.000000000000000000e+00,5.000000000000000000e+00,6.000000000000000000e+00

In [ ]:
# 使用二進位檔讀入， 使用load
import numpy as np

outputfile = "Example.npy"
with open(outputfile, 'rb') as fp:
    a = np.load(fp)
print(a)

In [68]:
# 使用CSV檔讀入， 使用loadtxt
import numpy as np

outputfile = "Example.out"
a = np.loadtxt(outputfile, delimiter=',')
print(a)
print()

b = a.astype(int)
print(b)

[[ 1.  2.  3.]
 [ 4.  5.  6.]]

[[1 2 3]
 [4 5 6]]


In [ ]:
參考書目：

陳允傑（2018）。Python資料科學與人工智慧應用實務。 台北：旗標。